# Generated by Django 4.2.13 on 2024-07-10 19:31

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('core', '0002_role_appitytoken_usertoclient_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appitytoken',
            options={'verbose_name': 'Appity-Token'},
        ),
        migrations.AddField(
            model_name='service',
            name='appointment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='booking.appointment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigIntegerField(default=core.utils.RandomId('core.Services'), primary_key=True, serialize=False, unique=True),
        ),
    ]
