# Generated by Django 4.2.13 on 2024-07-11 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_availability_user'),
        ('core', '0003_alter_appitytoken_options_service_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='booking.appointment'),
        ),
    ]
