# Generated by Django 4.2.13 on 2024-07-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_client_alter_service_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
    ]
