# Generated by Django 4.2.13 on 2024-07-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_client_first_name_remove_client_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoclient',
            name='roles',
        ),
    ]
