# Generated by Django 4.2.13 on 2024-07-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_usertoclient_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='currency',
        ),
    ]
