# Generated by Django 4.2.13 on 2024-07-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration', models.IntegerField()),
                ('access', models.CharField(choices=[(1, 'Public'), (0, 'Private')], default=0, max_length=50)),
            ],
        ),
    ]
