# Generated by Django 4.2.13 on 2024-07-10 19:31

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigIntegerField(default=core.utils.RandomId('booking.Appointment'), primary_key=True, serialize=False, unique=True)),
                ('appointment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'appointment',
                'verbose_name_plural': 'appointments',
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigIntegerField(default=core.utils.RandomId('booking.Availability'), primary_key=True, serialize=False, unique=True)),
                ('day_of_week', models.IntegerField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'availabilities',
            },
        ),
    ]
